/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jautopecas.crud;

import jautopecas.dao.GrupoDao;
import jautopecas.dao.pessoa.EmpresaDao;
import jautopecas.entidades.pessoa.Empresa;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.eclipse.persistence.exceptions.DatabaseException;

/**
 *
 * @author JFFiorotto
 */
public class FormularioEmpresa extends javax.swing.JPanel implements IFormulario {

    /**
     * Creates new form formularioEmpresa
     */
    public FormularioEmpresa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfIdEmpresa = new jautopecas.components.JFTextField();
        jtfRazaoSocial = new jautopecas.components.JFTextField();
        jlIdEmpresa = new javax.swing.JLabel();
        jlRazaoSocial = new javax.swing.JLabel();
        jtfNomeFantasia = new jautopecas.components.JFTextField();
        jlNomeFantasia = new javax.swing.JLabel();
        jtfCnpj = new jautopecas.components.JFTextField();
        jlCnpj = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 250));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtfIdEmpresa.setEditable(false);
        jtfIdEmpresa.setEnabled(false);
        jtfIdEmpresa.setMensagemAjuda("ID Empresa (Gerado pelo sistema)");
        add(jtfIdEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 60, -1));

        jtfRazaoSocial.setMensagemAjuda("Razão Social da empresa");
        add(jtfRazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 77, 332, -1));

        jlIdEmpresa.setText("ID Empresa");
        add(jlIdEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jlRazaoSocial.setText("Razão Social");
        add(jlRazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, 333, -1));

        jtfNomeFantasia.setMensagemAjuda("Nome Fantasia da empresa");
        add(jtfNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 333, -1));

        jlNomeFantasia.setText("Nome Fantasia");
        add(jlNomeFantasia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, 333, -1));

        jtfCnpj.setMensagemAjuda("CNPJ da empresa");
        add(jtfCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 31, 267, -1));

        jlCnpj.setText("CNPJ");
        add(jlCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 11, 267, -1));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlCnpj;
    private javax.swing.JLabel jlIdEmpresa;
    private javax.swing.JLabel jlNomeFantasia;
    private javax.swing.JLabel jlRazaoSocial;
    private jautopecas.components.JFTextField jtfCnpj;
    private jautopecas.components.JFTextField jtfIdEmpresa;
    private jautopecas.components.JFTextField jtfNomeFantasia;
    private jautopecas.components.JFTextField jtfRazaoSocial;
    // End of variables declaration//GEN-END:variables
    private Empresa empresa;

    @Override
    public void setObjetoFormulario(Object objetoFormulario) {
        empresa = (Empresa) objetoFormulario;
        jtfIdEmpresa.setText(String.valueOf(empresa.getIdPessoa()));
        jtfCnpj.setText(empresa.getCnpj());
        jtfRazaoSocial.setText(empresa.getRazaoSocial());
        jtfNomeFantasia.setText(empresa.getNomeFantasia());
    }

    @Override
    public void salvar() throws Exception {
        try {
            empresa = new Empresa();
            new EmpresaDao().salvar(getObjetoFormulario());
            setObjetoFormulario(empresa);

            JOptionPane.showMessageDialog(this, "Empresa Salvo com Sucesso!");
        } catch (Exception ex) {
            if (ex.getCause() instanceof DatabaseException) {
                if (((DatabaseException) ex.getCause()).getDatabaseErrorCode() == 1062) {
                    throw new Exception("Já existe um registro com estas informações!", ex);
                }
            } else {
                throw new Exception("Erro ao salvar a Empresa!!", ex);
            }
        }
    }

    @Override
    public void alterar() {
        try {
            new EmpresaDao().alterar(getObjetoFormulario());
            setObjetoFormulario(empresa);

            JOptionPane.showMessageDialog(this, "Empresa alterada com sucesso!!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao alterar a Empresa!!");
        }
    }

    @Override
    public void excluir() {
        try {
            new EmpresaDao().excluir(empresa);

            JOptionPane.showMessageDialog(this, "Grupo excluido com sucesso!!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o Grupo!!");
        }
    }

    @Override
    public Empresa getObjetoFormulario() {
        empresa.setIdPessoa(Long.valueOf(jtfIdEmpresa.getText().length() == 0 ? "0" : jtfIdEmpresa.getText()));
        empresa.setRazaoSocial(jtfRazaoSocial.getText());
        empresa.setNomeFantasia(jtfNomeFantasia.getText());
        empresa.setCnpj(jtfCnpj.getText());
        return empresa;
    }

    @Override
    public JLabel getJlInformacao() {
        return ((WindowCrud) getTopLevelAncestor()).getJlInformacao();
    }

    @Override
    public List pesquisar(String strPesquisa) {
        return new GrupoDao().listarTodos();
    }

    public List pesquisaSimples(String strCamposPesqisa, String strPesquisa) {
        return new EmpresaDao().pesquisaSimples(strCamposPesqisa, strPesquisa);
    }
}
