package jautopecas.crud.pessoa.endereco;

import jautopecas.components.JFTextField;
import jautopecas.components.validadores.ValidadorStringLength;
import jautopecas.entidades.pessoa.Pessoa;
import jautopecas.entidades.pessoa.endereco.Bairro;
import jautopecas.entidades.pessoa.endereco.Cidade;
import jautopecas.entidades.pessoa.endereco.Endereco;
import jautopecas.entidades.pessoa.endereco.Estado;
import java.awt.Component;
import java.awt.Container;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTextArea;

/**
 *
 * @author JFFiorotto
 */
public class CadEnderecoGUI extends javax.swing.JPanel {

    private CadEnderecoTableModel tableModel;
    private List<Endereco> enderecos;
    private Endereco endereco;
    private Pessoa pessoa;

    /**
     * Creates new form CadEnderecoGUI
     */
    public CadEnderecoGUI() {
        initComponents();

        jTable1.setModel(tableModel == null ? new CadEnderecoTableModel() : tableModel);
        jTable1.addMouseListener(
                new MouseAdapter() {

                    @Override
                    public void mouseClicked(MouseEvent e) {
                        try {
                            endereco = ((CadEnderecoTableModel) jTable1.getModel()).buscaProduto(jTable1.getSelectedRow());
                            setObjetoFormulario(endereco);
                        } catch (Exception ex) {
                        }
                    }
                });
    }

    public void setaCombo(JComboBox combo, String id) {
        for (int i = 0; i < combo.getItemCount(); i++) {
            String str = combo.getItemAt(i).toString();
            if (str.equals(id)) { // comparo  um valor do Objeto passado no parametro com um banco...  
                combo.setSelectedIndex(i);// quando meus 2 valores forem igual eu vou ter a posicao  do meu banco no combo.   
            }
        }
    }

    private Endereco getObjetoFormulario() {
        if (endereco == null) {
            endereco = new Endereco();
        }
        endereco.setUf((Estado) jtfUf.getObjeto());
        endereco.setBairro((Bairro) jtfBairro.getObjeto());
        endereco.setCidade((Cidade) jtfCidade.getObjeto());
        endereco.setCep(jtfCep.getText());
        endereco.setLogradouro(jtfLogradouro.getText());
        endereco.setTipoLogradouro(jcbTipoLogradouro.getSelectedItem().toString());
        endereco.setNumero(jtfNumero.getText());
        endereco.setPessoa(pessoa);
        return endereco;
    }
    private int countErrosFormulario;

    private void setObjetoFormulario(Endereco objetoFormulario) throws Exception {
        try {
            setaCombo(jcbTipoLogradouro, objetoFormulario.getTipoLogradouro());
            jtfLogradouro.setText(objetoFormulario.getLogradouro());
            jtfUf.setObjeto(objetoFormulario.getUf());
            jtfCidade.setObjeto(objetoFormulario.getCidade());
            jtfBairro.setObjeto(objetoFormulario.getBairro());
            jtfNumero.setText(objetoFormulario.getNumero());
            jtfCep.setText(objetoFormulario.getCep());
        } catch (Exception ex) {
            throw ex;
        }
    }

    private boolean validarFormulario(Container container, boolean recursive) {
        if (recursive) {
            countErrosFormulario = 0;
        }
        Component components[] = container.getComponents();
        for (Component component : components) {
            if (component instanceof JFormattedTextField) {
                JFormattedTextField field = (JFormattedTextField) component;
                field.setValue(null);
            } else if (component instanceof JFTextField) {
                JFTextField field = (JFTextField) component;
                if (!field.validaCampo()) {
                    countErrosFormulario++;
                }
            } else if (component instanceof JTextArea) {
                JTextArea area = (JTextArea) component;
                area.setText("");
            } else if (component instanceof Container) {
                validarFormulario((Container) component, false);
            }
        }
        return countErrosFormulario > 0 ? false : true;
    }

    /*
     * Geter's and Seter's
     */
    public void setListaEnderecos(List<Endereco> listaEnderecos) {
        this.enderecos = listaEnderecos;
        populaListaEnderecos();
    }

    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbTipoLogradouro = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlUf = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jcbTipoEndereco = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jbSalvar = new javax.swing.JButton();
        jbLimpar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jtfLogradouro = new jautopecas.components.JFTextField();
        jtfCep = new jautopecas.components.JFTextField();
        jtfNumero = new jautopecas.components.JFTextField();
        jtfUf = new jautopecas.components.JFTextField();
        jtfCidade = new jautopecas.components.JFTextField();
        jtfBairro = new jautopecas.components.JFTextField();

        jcbTipoLogradouro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AVENIDA", "BECO", "BLOCO", "CAMINHO", "LADEIRA", "LARGO", "PRAÇA", "PARQUE", "PRAIA", "QUILOMETRO", "QUINTA", "RODOVIA", "RUA", "SUPER QUADRA", "TRAVESSA", "AEROPORTO", "ALAMEDA", "ESCADA", "ESTAÇÃO", "ESTRADA", "FAZENDA", "FORTALEZA", "GALERIA", "QUADRA", "VIADUTO", "VILA", "ROTARY", "VALE", "VIA" }));

        jLabel1.setText("Tipo Logradouro");

        jLabel2.setText("Logradouro");

        jLabel3.setText("Numero");

        jLabel4.setText("Cep");

        jLabel5.setText("Bairro");

        jLabel6.setText("Cidade");

        jlUf.setText("Estado");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jcbTipoEndereco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comercial", "Residencial", "Faturamento", "Entrega" }));

        jLabel8.setText("Tipo Endereço");

        jbSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jautopecas/imagens/icones/iconeConfirmar24.png"))); // NOI18N
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jautopecas/imagens/icones/iconeLimpar24.png"))); // NOI18N
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jautopecas/imagens/icones/iconeDeletar24.png"))); // NOI18N
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jtfLogradouro.setMensagemAjuda("Logradouro");
        jtfLogradouro.setValidador(new ValidadorStringLength(jtfLogradouro, 10, 150));

        jtfCep.setMensagemAjuda("Codigo de endereçamento postal");
        jtfCep.setValidador(new ValidadorStringLength(jtfCep, 8, 8));

        jtfNumero.setMensagemAjuda("Numero");
        jtfNumero.setValidador(new ValidadorStringLength(jtfNumero, 1, 10));

        jtfUf.setClasseFormulario("jautopecas.crud.pessoa.endereco.FormularioEstado");
        jtfUf.setMensagemAjuda("Codigo de endereçamento postal");
        jtfUf.setValidador(new ValidadorStringLength(jtfCep, 8, 8));

        jtfCidade.setClasseFormulario("jautopecas.crud.pessoa.endereco.FormularioCidade");
        jtfCidade.setMensagemAjuda("Codigo de endereçamento postal");
        jtfCidade.setValidador(new ValidadorStringLength(jtfCep, 8, 8));

        jtfBairro.setClasseFormulario("jautopecas.crud.pessoa.endereco.FormularioBairro");
        jtfBairro.setMensagemAjuda("Codigo de endereçamento postal");
        jtfBairro.setValidador(new ValidadorStringLength(jtfCep, 8, 8));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(90, 90, 90)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jcbTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2)
                                .addGap(349, 349, 349)
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jcbTipoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(122, 122, 122)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlUf)
                                        .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfUf, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvar)
                        .addGap(6, 6, 6)
                        .addComponent(jbLimpar)
                        .addGap(6, 6, 6)
                        .addComponent(jbExcluir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jcbTipoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbTipoLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUf)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalvar)
                    .addComponent(jbLimpar)
                    .addComponent(jbExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        if (validarFormulario(this, true)) {
            Endereco endereco = getObjetoFormulario();
            if (endereco.getIdEndereco() == null) {
                enderecos.add(endereco);
            } else {
                enderecos.set(jTable1.getSelectedRow(), endereco);
            }

            populaListaEnderecos();
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        enderecos.remove(jTable1.getSelectedRow());
        populaListaEnderecos();
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbLimparActionPerformed

    private void populaListaEnderecos() {
        ((CadEnderecoTableModel) jTable1.getModel()).removeResultado();
        ((CadEnderecoTableModel) jTable1.getModel()).mostraResultado(enderecos);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcbTipoEndereco;
    private javax.swing.JComboBox jcbTipoLogradouro;
    private javax.swing.JLabel jlUf;
    private jautopecas.components.JFTextField jtfBairro;
    private jautopecas.components.JFTextField jtfCep;
    private jautopecas.components.JFTextField jtfCidade;
    private jautopecas.components.JFTextField jtfLogradouro;
    private jautopecas.components.JFTextField jtfNumero;
    private jautopecas.components.JFTextField jtfUf;
    // End of variables declaration//GEN-END:variables
}
